### ISSUE TITLE
实际应用场景兼容性问题

### ISSUE THREAD

**Issue by komomon** [JKme/cube#4]
不知道师傅有没有注意到，一般机器使用会出现的报错，缺少库
./cube_linux_amd64: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./cube_linux_amd64)
./cube_linux_amd64: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./cube_linux_amd64)
xray和naabu较新的多个版本一样有这个问题，但是该工具定位是内网使用的工具，不太可能说我提权到root再去下glibc包，编译再运行，这是不现实的，一般的centos debian10 debian11，是默认不会装这么高版本的glibc库的。建议修改下配置提高下实际使用场景下的兼容性。

**Comment by JKme** [comment]
CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags "-s -w" -trimpath main.go
我本地测试可行，你试试功能正常不正常，正常我就修改编译配置了。

参考链接:
- https://www.reddit.com/r/golang/comments/u9educ/glibc_mismatch_when_compiling_locally_then/

**Comment by stream1990** [comment]
> CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags "-s -w" -trimpath main.go 我本地测试可行，你试试功能正常不正常，正常我就修改编译配置了。
> 
> 参考链接:
> 
> * https://www.reddit.com/r/golang/comments/u9educ/glibc_mismatch_when_compiling_locally_then/

师傅，还有个问题，用字典的时候，密码里的{user}没有替换，只有用默认的时候才会替换

**Comment by stream1990** [comment]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x911691]

goroutine 40 [running]:
cube/core/crackmodule.Phpmyadmin.Exec({0xc00004c800?})
	cube/core/crackmodule/phpmyadmin.go:103 +0x1091
cube/core/crackmodule.runSingleTask({0xda21b0, 0xc0000ac000}, 0xc000976000, 0xc0005e3043?, 0x0)
	cube/core/crackmodule/crack_task.go:168 +0x3b5
created by cube/core/crackmodule.StartCrack
	cube/core/crackmodule/crack_task.go:243 +0x528

 status 2

**Comment by stream1990** [comment]
> > > CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags "-s -w" -trimpath main.go 我本地测试可行，你试试功能正常不正常，正常我就修改编译配置了。
> > > 参考链接:
> > > 
> > > * https://www.reddit.com/r/golang/comments/u9educ/glibc_mismatch_when_compiling_locally_then/
> > 
> > 
> > 师傅，还有个问题，用字典的时候，密码里的{user}没有替换，只有用默认的时候才会替换
> 
> 默认不指定用户密码是会替换的，如果指定了用户密码就不会用内置的词典规则，这时候就不替换了。

https://github.com/JKme/cube/blob/master/core/crackmodule/httpbasic.go
师傅，if res.StatusCode != 401 {
			result.Result = true
		}这样判断好像也不行，像tomcat，很多都是403，没权限的，这种全会当成成功呢

**Comment by stream1990** [comment]
> > > > CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags "-s -w" -trimpath main.go 我本地测试可行，你试试功能正常不正常，正常我就修改编译配置了。
> > > > 参考链接:
> > > > 
> > > > * https://www.reddit.com/r/golang/comments/u9educ/glibc_mismatch_when_compiling_locally_then/
> > > 
> > > 
> > > 师傅，还有个问题，用字典的时候，密码里的{user}没有替换，只有用默认的时候才会替换
> > 
> > 
> > 默认不指定用户密码是会替换的，如果指定了用户密码就不会用内置的词典规则，这时候就不替换了。
> 
> https://github.com/JKme/cube/blob/master/core/crackmodule/httpbasic.go 师傅，if res.StatusCode != 401 { result.Result = true }这样判断好像也不行，像tomcat，很多都是403，没权限的，这种全会当成成功呢

401的师傅可以先访问一次，如果不是401就直接跳过本次任务。phpmyadmin的用302来判断好像不行，很多错误也是302回主页。比如。http://103.48.116.113/phpmyadmin/

**Comment by JKme** [comment]
> > > > > CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags "-s -w" -trimpath main.go 我本地测试可行，你试试功能正常不正常，正常我就修改编译配置了。
> > > > > 参考链接:
> > > > > 
> > > > > * https://www.reddit.com/r/golang/comments/u9educ/glibc_mismatch_when_compiling_locally_then/
> > > > 
> > > > 
> > > > 师傅，还有个问题，用字典的时候，密码里的{user}没有替换，只有用默认的时候才会替换
> > > 
> > > 
> > > 默认不指定用户密码是会替换的，如果指定了用户密码就不会用内置的词典规则，这时候就不替换了。
> > 
> > 
> > https://github.com/JKme/cube/blob/master/core/crackmodule/httpbasic.go 师傅，if res.StatusCode != 401 { result.Result = true }这样判断好像也不行，像tomcat，很多都是403，没权限的，这种全会当成成功呢
> 
> 401的师傅可以先访问一次，如果不是401就直接跳过本次任务。phpmyadmin的用302来判断好像不行，很多错误也是302回主页。比如。http://103.48.116.113/phpmyadmin/

phpmyadmin现在用登录成功的页面字段检查，判断是否包含li_pma_wiki
httpbasic用的这个判断res.StatusCode >= 200 && res.StatusCode < 400

我寻思httpbasic这个还会有误报，phpmyadmin应该是没问题了，你多跑一跑，有任何问题随时联系我，微信: amtfZHVjaw==
